name: Release package

on:
  workflow_dispatch:
    inputs:
      version:
        description: "package version. format: [number.number.number]"
        required: true


jobs:
  deploy:
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          registry-url: "https://registry.npmjs.org"

      - name: install dependencies and build packages
        run: npm ci

      - name: set package version
        run: npm version ${{ github.event.inputs.version }} --allow-same-version true --git-tag-version false

      - name: github release
        run: gh release create ${{ github.event.inputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
